"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Justin Li"
email = "justinnhli@gmail.com"

[git]
colocate = false

[ui]
diff-editor = ":builtin"
conflict-marker-style = "snapshot"

[revset-aliases]
"hidden_bookmarks()" = "bookmarks(regex:'^hidden-')"
"visible_bookmarks()" = "bookmarks() ~ hidden_bookmarks()"
"visible_heads()" = "heads(::) ~ hidden_bookmarks() ~ untracked_remote_bookmarks()"
"closest_immutable(to)" = "heads(::to & immutable_heads())"
"log_revset()" = "ancestors(@, 3) | closest_immutable(@) | visible_heads() | visible_bookmarks() | conflicts()"

[revsets]
log = "fork_point(log_revset()) | log_revset()"

[aliases]
clone = ["git", "clone"]
gc = ["util", "gc"]
fetch = ["git", "fetch"]
"new+" = ["new", "--insert-after", "@"]
"new-" = ["new", "--insert-before", "@"]
loga = ["log", "-r", "::"]
logn = ["log", "-r", "present(@) | ancestors(immutable_heads().., 2) | present(trunk())"]
push = ["git", "push"]
tug = ["bookmark", "advance", "--to", "@-"]

[templates]
draft_commit_description = '''
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
